<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => 'fisiocampo',
	'db_port' => '3306',
	'db_name' => 'fisiocampo',
	'db_user' => 'root',
	'db_password' => null,
	'db_backup_tables' => 1,
	'db_backup_prefix' => 'bak_fisiocampo',
	'mailer_from_name' => 'Joaquin Carmona',
	'mailer_from_email' => 'jozic.daniel21@gmail.com',
	'mailer_transport' => 'smtp',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_amazon_region' => 'us-east-1',
	'mailer_amazon_other_region' => null,
	'mailer_api_key' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/../var/spool',
	'secret_key' => '3263e86ebc9501545c3e52c8613d1dff08cc9b01f118139859e80d33c64d87af',
	'site_url' => 'http://fisiocampo-local.com/marketing',
);
