<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHxuobzm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHxuobzm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHxuobzm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHxuobzm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHxuobzm\appProdProjectContainer([
    'container.build_hash' => 'Hxuobzm',
    'container.build_id' => '0c64e224',
    'container.build_time' => 1608759779,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHxuobzm');
